services:
  vvis:
    environment:
      WEBIP:   "0.0.0.0"
      WEBPORT: "8000"
      EXAMPLE_CLINET_CONN: "ws://127.0.0.1:8001/"
      EXAMPLE_IM_CLIENT_CONN: "ws://127.0.0.1:8002/"
      ALLOWED_HOSTS: "127.0.0.1,localhost"
      SECRET_KEY: "fake_secret_key"
      DEBUG: "true"
    image: philipdavis82/visgui.server
    ports:
      - '8000:8000'
    volumes:
      - ./server:/vvis
    # build:
      # context: server-aio
    build:
      context: server-django
    command : sh -c "python manage.py runserver 0.0.0.0:8000"
  example:
    environment:
      WEBIP:   "0.0.0.0"
      WEBPORT: "8000"
    build:
      context: example/websocket_server
    image: philipdavis82/visgui.example.websocket
    ports:
      - '8001:8000'
  example_im:
    environment:
      WEBIP:   "0.0.0.0"
      WEBPORT: "8000"
    build:
      context: example_im/websocket_server
    image: philipdavis82/visgui.example_im.websocket
    ports:
      - '8002:8000'
  