services:
  http:
    build:
      context: server
    image: philipdavis82/visgui.server
    ports:
      - '8000:8000'
  example:
    build:
      context: example/websocket_server
    image: philipdavis82/visgui.example.websocket
    ports:
      - '8001:8000'
  example_im:
    build:
      context: example_im/websocket_server
    image: philipdavis82/visgui.example_im.websocket
    ports:
      - '8002:8000'
  